name: '定时发送天气报告'

on:
  push:
  schedule:
    - cron: '0 22 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: '[1]Checkout codes'
        uses: actions/checkout@v1
      - name: '[2]Get Result'
        run: bash ./weather.sh
      - name: '[3]Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.126.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Shanghai Weather Report
          body: file://result.html
          to: akqdream@foxmail.com
          from: GitHub Actions
          content_type: text/html
